global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using TechShop.ECommerce.Application.Contracts.Persistence;
global using TechShop.ECommerce.Domain.Common;
global using TechShop.ECommerce.Domain.Entities;
global using TechShop.ECommerce.Persistence.DatabaseContext;
global using TechShop.ECommerce.Persistence.Repositories;
