<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>cbd57680-6124-4165-9769-6252ceee42f7</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>		
		<PackageReference Include="AutoMapper" Version="16.1.1" />		
		<PackageReference Include="Hangfire.PostgreSql" Version="1.21.1" />		
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.5">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.0.5" />
		<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.15.0" />
		<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.15.0" />
		<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.15.1" />
		<PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" Version="1.15.0-beta.1" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.15.0" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.15.0" />
		<PackageReference Include="Scalar.AspNetCore" Version="2.12.34" />
		<PackageReference Include="Serilog" Version="4.3.0" />
		<PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
		<PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0" />
		<PackageReference Include="Serilog.Settings.Configuration" Version="10.0.0" />
		<PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
		<PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
		<PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
		<PackageReference Include="Serilog.Sinks.Seq" Version="9.0.0" />
		<PackageReference Include="xunit" Version="2.9.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Core\TechShop.ECommerce.Application\TechShop.ECommerce.Application.csproj" />
		<ProjectReference Include="..\..\Infrastructure\TechShop.ECommerce.Identity\TechShop.ECommerce.Identity.csproj" />
		<ProjectReference Include="..\..\Infrastructure\TechShop.ECommerce.Infrastructure\TechShop.ECommerce.Infrastructure.csproj" />
		<ProjectReference Include="..\..\Infrastructure\TechShop.ECommerce.Persistence\TechShop.ECommerce.Persistence.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="logs\" />
	</ItemGroup>

</Project>
